# Generated by Django 5.0.4 on 2024-05-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registrationid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('course', models.CharField(max_length=100, unique=True)),
                ('parentname', models.CharField(max_length=100, unique=True)),
                ('parentsurname', models.CharField(max_length=100, unique=True)),
                ('parentemail', models.CharField(max_length=100, unique=True)),
                ('parentphonenumber', models.CharField(max_length=100, unique=True)),
                ('studentname', models.CharField(max_length=100, unique=True)),
                ('studentsurname', models.CharField(max_length=100, unique=True)),
                ('studentsex', models.CharField(max_length=100, unique=True)),
                ('form', models.CharField(max_length=100, unique=True)),
                ('registrationdate', models.DateTimeField(verbose_name='startdate')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
        ),
    ]
