# Generated by Django 5.0.4 on 2024-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_registration_course_alter_registration_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
