# Generated by Django 5.0.4 on 2024-05-31 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('data', '0003_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('popid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pop', models.ImageField(blank=True, upload_to='static/pop')),
                ('popuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
                ('registration', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.registration')),
            ],
        ),
    ]
