# Generated by Django 5.0.4 on 2024-06-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('data', '0004_pop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admissionid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('admissionuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
                ('registration', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.registration')),
            ],
        ),
    ]
