# Generated by Django 5.0.4 on 2024-06-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('data', '0005_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('feedbackrating', models.CharField(max_length=100)),
                ('feedbackcomment', models.CharField(max_length=100)),
                ('feedbackuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
        ),
    ]
