# Generated by Django 5.0.4 on 2024-06-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('contactname', models.CharField(max_length=100)),
                ('contactcompany', models.CharField(max_length=100)),
                ('contactcompanyemployees', models.CharField(max_length=100)),
                ('contactbusiness', models.CharField(max_length=100)),
            ],
        ),
    ]
