# Generated by Django 5.0.4 on 2024-06-03 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('addid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('addimage', models.ImageField(blank=True, upload_to='static/addimage')),
                ('adduser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
        ),
    ]
