# Generated by Django 5.0.4 on 2024-06-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('affiliateprogram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('promocodeid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('promocode', models.CharField(max_length=100)),
                ('promocodeuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
        ),
    ]
