# Generated by Django 5.0.4 on 2024-06-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('affiliateprogram', '0002_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('tokenid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=100)),
                ('tokenuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
        ),
    ]
