# Generated by Django 5.0.4 on 2024-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateprogram', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitationinvitee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitationinviteesurname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
